project_id = "yatqauonguxjrprcsfyx"

[functions.tarot-generate]
verify_jwt = false

[functions.fortune-generate]
verify_jwt = false

[functions.health]
verify_jwt = false

[functions.readings-test]
verify_jwt = false

[functions.readings-ai]
verify_jwt = false

[functions.storage-test-image-record]
verify_jwt = false
